#pragma once

#include <base.h>

enum COMMAND : u32
{
    COMMAND_NULL,
    COMMAND_SWITCH_BADPAINT_PIXEL_TYPE_TO_REMOVE,
    COMMAND_SWITCH_BADPAINT_PIXEL_TYPE_TO_MAX,
    COMMAND_SWITCH_BADPAINT_PIXEL_TYPE_TO_SHIFT,
    COMMAND_SWITCH_BADPAINT_PIXEL_TYPE_TO_RANDOM,
    COMMAND_SWITCH_BADPAINT_PIXEL_TYPE_TO_COPY_OTHER_PIXEL,
    COMMAND_SWITCH_TOOL_TO_PENCIL,
    COMMAND_SWITCH_TOOL_TO_ERASER,
    COMMAND_SWITCH_TOOL_TO_SPAYCAN,
    COMMAND_SWITCH_TOOL_TO_TEST,
    COMMAND_EXPORT_IMAGE,
    COMMAND_OPEN_IMPORT_DIALOGUE,
    COMMAND_IMPORT_FILE_PATH,
    COMMAND_PAINT_ON_CANVAS_BETWEEN_POSITIONS,
    COMMAND_COUNT,
};
